import 'package:flutter/material.dart';

const String HOST_API = 'https://localhost:7012';
const String TOKEN =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IsSQaW5oIFF1YW5nIEto4bqjaSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IkFkbWluaXN0cmF0b3IiLCJVc2VyX0lEIjoiNzczYTAzZjAtMTRjOC00MGIwLWIyOTItYzdkZmIyYTkwMDc4IiwiUm9sZV9JRCI6ImRiMDBmMGY2LTIzN2UtNDIxYy1iZjg2LTU3ZTdkZTBiMjVlZSIsIlRva2VuX0lEIjoiZmRlMmEzOWQtMTY4MS00ZDZlLTgzNjEtMjdmMjZkMjc5ZjZlIiwibmJmIjoxNzI3NDk1NjI2LCJleHAiOjE3Mjc1MTcyMjYsImlhdCI6MTcyNzQ5NTYyNn0.qVgks-oGkrBUjPaHZsCtDz3fd_QXMIlJzMo-am5pxYM';
const Color mainColor = Color.fromARGB(214, 21, 34, 153);
